### ISSUE TITLE
Some day buttons in cal panel are not selectable

### ISSUE THREAD

**Issue by jospic** [ivanskodje-godotengine/godot-plugin-calendar-button#1]
Great component. I'm trying it in my projects. There is an issue for the panel day buttons that come out of the parent window. They are not clickable. Is it a desired behavior? Any suggestions?
Thanks in advance.
-j

**Comment by ivanskodje** [comment]
Do you have any nodes that ~~stops~~ does not ignore the mouse clicks on top of it?
![image](https://cloud.githubusercontent.com/assets/6776092/24581443/c993ed6c-171b-11e7-95a5-4557dbe6f952.png)

By that I mean, do you have any GUI or other components (that you may not even see) on top of the calendar somewhere that might ~~stop~~ not ignore the mouse clicks? :)

**Comment by jospic** [comment]
Thanks for reply. I've disabled all "Stop Mouse" control in all UI controls, but the issue remains. The only buttons that not work are those outside the parent window, as shown in the figure. Those internal parent window works well..
![sshot](https://cloud.githubusercontent.com/assets/22050804/24581874/015de31c-1724-11e7-9127-7613036cfecb.png)

**Comment by ivanskodje** [comment]
Forgive me, I noticed I wrote "Stop Mouse", but it is "Ignore Mouse" that allows you to click through other nodes. Stop Mouse does not appear to do anything to prevent clicking the day buttons.
![image](https://cloud.githubusercontent.com/assets/6776092/24627378/f3e39406-18b4-11e7-9bd4-c401ea040ba5.png)

By the look of it, it looks like your table list somehow is on top of it. Could you redo what you are doing, and send me a screenshot of your live scene tree from the debugger? 

In case you are not familiar with it:
1. Run the program
2. Do everything you did to reach the point where you are not able to select days
3. In Godot Engine, check the "Debugger" tab and select the "Remote Inspector" tab. 

Inside the Remote Inspector you should be able to see the live scene tree. I suspect there is a node above it that steals the focus.

For example, when you hover your mouse over the buttons, do they lighten up?
My attempts to recreate the issue have failed.
![image](https://cloud.githubusercontent.com/assets/6776092/24627550/8dd09d7a-18b5-11e7-88fd-010d44447e7d.png)

The only way I am prevented to click the buttons, are when there is *something* on top of it that does not ignore mouse.

**Comment by jospic** [comment]
Thanks for your help. So, all the checks of the top ui controls that conflict with calendar buttons should have "Ignore Mouse" enabled?
Even with this change, the result does not change. However all buttons light up on mouse over, even those not working.

An other thing: in your example screenshot you have used a panel as parent for your calendar. In my case calendar parent is a "WindowDialog" popup. Have you tried on this?

I've made a little snippet Godot project that shows the issue:
https://github.com/jospic/test_calendar

Thanks a lot.
-j

**Comment by ivanskodje** [comment]
No, thank **you**. :)
I appreciate it when people point out bugs and errors when spotted.

I did some tests, and apparently it has nothing to do with the Calendar plugin button itself. 
Whenever you try to press a button (any Button) that is outside of the WindowDialog border, it won't allow you to press it.

Made an issue about it here https://github.com/godotengine/godot/issues/8295 on Godot's repo.

**Comment by ivanskodje** [comment]
Closing since this is not an issue with the Calendar plugin, but with the engine
